// <auto-generated />
using System;
using Mess_Management_System_Alpha_V2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mess_Management_System_Alpha_V2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190425040459_warehousestoreModelUpdate")]
    partial class warehousestoreModelUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("BUPEmail");

                    b.Property<string>("BUPEmployeTypeName");

                    b.Property<int>("BUPEmployeeID");

                    b.Property<string>("BUPFullName");

                    b.Property<string>("BUPGender");

                    b.Property<string>("BUPLogInID");

                    b.Property<string>("BUPPassword");

                    b.Property<string>("BUPPhone");

                    b.Property<string>("BUPRoleName");

                    b.Property<int>("BUPUser_ID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("MenuName");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MenuSub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName");

                    b.Property<string>("ControllerName");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<long>("MenuId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("SubMenuName");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("SubMenu");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.BillHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("BillHistory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<double>("Price");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("SetMenuId");

                    b.HasKey("Id");

                    b.HasIndex("SetMenuId");

                    b.ToTable("ExtraItem");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsAvailableForPreOrder");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Serial");

                    b.HasKey("Id");

                    b.ToTable("MealType");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OrderHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsPreOrder");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<long?>("MealTypeId");

                    b.Property<double>("OrderAmount");

                    b.Property<DateTime>("OrderDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("SetMenuId");

                    b.Property<long>("StoreOutItemId");

                    b.Property<double>("UnitOrdered");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("StoreOutItemId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.PreOrderSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsPreOrderSet");

                    b.Property<DateTime>("LastConfigurationUpdateDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PreOrderSchedule");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.RemainingBalanceAndWeightedPriceCalculation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInCategoryId");

                    b.Property<long?>("StoreInItemId");

                    b.Property<double>("TotalAvailableAmount");

                    b.Property<double>("WeightedPrice");

                    b.HasKey("Id");

                    b.HasIndex("StoreInCategoryId");

                    b.HasIndex("StoreInItemId");

                    b.ToTable("RemainingBalanceAndWeightedPriceCalculation");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsAvailableAsExtra");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Serial");

                    b.Property<DateTime>("SetMenuDate");

                    b.Property<decimal>("SetMenuPrice");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.ToTable("SetMenu");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenuDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("SetMenuId");

                    b.Property<long>("StoreOutItemId");

                    b.HasKey("Id");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("SetMenuDetails");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsOpen");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInCategoryId");

                    b.Property<long>("UnitTypeId");

                    b.HasKey("Id");

                    b.HasIndex("StoreInCategoryId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("StoreInItem");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("StoreInItemCategory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsOpen");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<double>("MinimumProductionUnit");

                    b.Property<double>("MinimumProductionUnitMultiplier");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreOutCategoryId");

                    b.Property<long>("UnitTypeId");

                    b.HasKey("Id");

                    b.HasIndex("StoreOutCategoryId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("StoreOutItem");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("StoreOutItemCategory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemRecipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<double>("MinimumStoreOutUnit");

                    b.Property<double>("RequiredStoreInUnit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInItemId");

                    b.Property<long>("StoreOutItemId");

                    b.HasKey("Id");

                    b.HasIndex("StoreInItemId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("StoreOutItemRecipe");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.UnitType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("ShortName");

                    b.HasKey("Id");

                    b.ToTable("UnitType");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.WarehouseStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsStoreOut");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInItemId");

                    b.HasKey("Id");

                    b.HasIndex("StoreInItemId");

                    b.ToTable("WarehouseStorage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MenuSub", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.Menu", "Menu")
                        .WithMany("SubMenuList")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("ExtraItemList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OrderHistory", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.PreOrderSchedule", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("PreOrderScheduleList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("PreOrderScheduleList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.RemainingBalanceAndWeightedPriceCalculation", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItemCategory", "StoreInItemCategory")
                        .WithMany()
                        .HasForeignKey("StoreInCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem")
                        .WithMany("RemainingBalanceAndWeightedPriceCalculationList")
                        .HasForeignKey("StoreInItemId");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("SetMenuList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenuDetails", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("SetMenuDetailsList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("SetMenuDetailsList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItemCategory", "StoreInItemCategory")
                        .WithMany("StoreInItemList")
                        .HasForeignKey("StoreInCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemCategory", "StoreOutItemCategory")
                        .WithMany("StoreOutItemList")
                        .HasForeignKey("StoreOutCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemRecipe", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", "StoreInItem")
                        .WithMany("StoreOutItemRecipeList")
                        .HasForeignKey("StoreInItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("StoreOutItemRecipeList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.WarehouseStorage", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", "StoreInItem")
                        .WithMany("WarehouseStorageList")
                        .HasForeignKey("StoreInItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
