// <auto-generated />
using System;
using Mess_Management_System_Alpha_V2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mess_Management_System_Alpha_V2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210129064317_NewBillTask")]
    partial class NewBillTask
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("BUPEmail");

                    b.Property<string>("BUPEmployeTypeName");

                    b.Property<int>("BUPEmployeeID");

                    b.Property<string>("BUPFullName");

                    b.Property<string>("BUPGender");

                    b.Property<string>("BUPLogInID");

                    b.Property<string>("BUPPassword");

                    b.Property<string>("BUPPhone");

                    b.Property<string>("BUPRoleName");

                    b.Property<int>("BUPUser_ID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("MenuName");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MenuSub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName");

                    b.Property<string>("ControllerName");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<long>("MenuId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("SubMenuName");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("SubMenu");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.AccessoryBill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<double?>("CostMinMeal");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double>("DefaultCost");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int?>("MinMeal");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("AccessoryBill");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.BillHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("BillHistory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.Constants", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Constants");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerBillHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attribute1");

                    b.Property<string>("Attribute2");

                    b.Property<long>("ConsumerBillParentId");

                    b.Property<long>("ConsumerPaymentInfoId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double>("Due");

                    b.Property<bool>("IsPartial");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<double>("PaymentAmount");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<string>("ReceivedBy");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("TransactionID");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerBillParentId");

                    b.HasIndex("ConsumerPaymentInfoId");

                    b.ToTable("ConsumerBillHistory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerBillParent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attribute1");

                    b.Property<string>("Attribute2");

                    b.Property<string>("Attribute3");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConsumerBillParent");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerMealWiseExtraChitParent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attribute1");

                    b.Property<string>("Attribute2");

                    b.Property<string>("Attribute3");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<long>("OrderTypeId");

                    b.Property<string>("Remarks");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ConsumerMealWiseExtraChitParent");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerMealWiseExtrachit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ConsumerMealWiseExtraChitParentId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreOutItemId");

                    b.Property<double?>("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerMealWiseExtraChitParentId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("ConsumerMealWiseExtrachit");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerMonthlyBillRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsPaid");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int>("Month");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<double>("TotalAmount");

                    b.Property<string>("UserId");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConsumerMonthlyBillRecord");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerPaymentInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber");

                    b.Property<string>("Attribute1");

                    b.Property<string>("Attribute2");

                    b.Property<string>("Attribute3");

                    b.Property<string>("BankName");

                    b.Property<long>("ConsumerBillParentId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("MobileNumber");

                    b.Property<long>("PaymentMethodId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("ConsumerBillParentId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("ConsumerPaymentInfo");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.CustomerChoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<long?>("ExtraItemId");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<long>("OrderTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("SetMenuId");

                    b.Property<string>("UserId");

                    b.Property<double>("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ExtraItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerChoice");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.CustomerChoiceV2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<long>("ExtraChitParentId");

                    b.Property<long?>("ExtraItemId");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<long>("OnSpotParentId");

                    b.Property<long>("OrderTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("SetMenuId");

                    b.Property<string>("UserId");

                    b.Property<double>("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ExtraChitParentId");

                    b.HasIndex("ExtraItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("OnSpotParentId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerChoiceV2");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.CustomerDailyMenuChoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Day");

                    b.Property<long?>("ExtraItemId");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<long>("OrderTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.Property<double>("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ExtraItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerDailyMenuChoice");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.DailySetMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Day");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime?>("SetMenuDate");

                    b.Property<long>("SetMenuId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("SetMenuId");

                    b.ToTable("DailySetMenu");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraChitParent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("ExtraChitParent");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("Day");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long?>("MealTypeId");

                    b.Property<DateTime>("MenuDate");

                    b.Property<double>("Price");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("SetMenuId");

                    b.Property<long>("StoreOutItemId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("ExtraItem");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.MaintenanceBillHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BillAmount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int>("Month");

                    b.Property<string>("Remarks");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.Property<long>("Year");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MaintenanceBillHistory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsAvailableForPreOrder");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PreOrderLastTime");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Serial");

                    b.HasKey("Id");

                    b.ToTable("MealType");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Day");

                    b.Property<long?>("ExtraItemId");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long?>("MealTypeId");

                    b.Property<double>("Price");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("StoreOutItemId");

                    b.HasKey("Id");

                    b.HasIndex("ExtraItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.Office", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OnSpotParent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BearerId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsOfficeOrder");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long?>("OfficeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.HasIndex("UserId");

                    b.ToTable("OnSpotParent");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OrderHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("ForwardRemarks");

                    b.Property<bool?>("IsForwardedToOffice");

                    b.Property<bool>("IsPreOrder");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<double>("OrderAmount");

                    b.Property<DateTime>("OrderDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("SetMenuId");

                    b.Property<long?>("StoreOutItemId");

                    b.Property<double>("UnitOrdered");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("StoreOutItemId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OrderHistoryVr2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("ForwardRemarks");

                    b.Property<bool?>("IsForwardedToOffice");

                    b.Property<bool>("IsPreOrder");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<double>("OrderAmount");

                    b.Property<DateTime>("OrderDate");

                    b.Property<long?>("OrderTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("SetMenuId");

                    b.Property<long?>("StoreOutItemId");

                    b.Property<double>("UnitOrdered");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("StoreOutItemId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderHistoryVr2");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OrderType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("OrderType");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.PaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("MethodName");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.Period", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("From");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("To");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Period");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.PreOrderSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsPreOrderSet");

                    b.Property<DateTime>("LastConfigurationUpdateDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("SetMenuId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("UserId");

                    b.ToTable("PreOrderSchedule");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.RemainingBalanceAndWeightedPriceCalculation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInItemId");

                    b.Property<double>("TotalAvailableAmount");

                    b.Property<double>("WeightedPrice");

                    b.HasKey("Id");

                    b.HasIndex("StoreInItemId");

                    b.ToTable("RemainingBalanceAndWeightedPriceCalculation");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("Day");

                    b.Property<bool>("IsAvailableAsExtra");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Serial");

                    b.Property<DateTime>("SetMenuDate");

                    b.Property<decimal>("SetMenuPrice");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.ToTable("SetMenu");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenuDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long?>("ExtraItemId");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("SetMenuId");

                    b.Property<long>("StoreOutItemId");

                    b.HasKey("Id");

                    b.HasIndex("ExtraItemId");

                    b.HasIndex("SetMenuId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("SetMenuDetails");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SpecialMenuOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("SpecialMenuParentId");

                    b.Property<long?>("StoreOutItemId");

                    b.Property<double>("UnitOrdered");

                    b.HasKey("Id");

                    b.HasIndex("SpecialMenuParentId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("SpecialMenuOrder");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SpecialMenuParent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<long?>("OfficeId");

                    b.Property<DateTime>("OrderDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("UserId");

                    b.ToTable("SpecialMenuParent");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsOpen");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInCategoryId");

                    b.Property<long>("UnitTypeId");

                    b.HasKey("Id");

                    b.HasIndex("StoreInCategoryId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("StoreInItem");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("StoreInItemCategory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("Day");

                    b.Property<bool>("IsOpen");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int?>("MealTypeId");

                    b.Property<double>("MinimumProductionUnit");

                    b.Property<double>("MinimumProductionUnitMultiplier");

                    b.Property<string>("Name");

                    b.Property<double?>("Price");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreOutCategoryId");

                    b.Property<long>("UnitTypeId");

                    b.HasKey("Id");

                    b.HasIndex("StoreOutCategoryId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("StoreOutItem");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("StoreOutItemCategory");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemRecipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<double>("MinimumStoreOutUnit");

                    b.Property<double>("RequiredStoreInUnit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInItemId");

                    b.Property<long>("StoreOutItemId");

                    b.HasKey("Id");

                    b.HasIndex("StoreInItemId");

                    b.HasIndex("StoreOutItemId");

                    b.ToTable("StoreOutItemRecipe");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.TestClassMod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cost");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("TestClassMod");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.UnitType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("ShortName");

                    b.HasKey("Id");

                    b.ToTable("UnitType");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.UserDateChoiceDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsOrderSet");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long?>("UserDateChoiceMasterId");

                    b.HasKey("Id");

                    b.HasIndex("UserDateChoiceMasterId");

                    b.ToTable("UserDateChoiceDetail");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.UserDateChoiceMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("MealTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDateChoiceMaster");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.WarehouseStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsStoreOut");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<double>("PurchaseRate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<long>("StoreInItemId");

                    b.Property<double>("TotalPurchasePrice");

                    b.HasKey("Id");

                    b.HasIndex("StoreInItemId");

                    b.ToTable("WarehouseStorage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MenuSub", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.Menu", "Menu")
                        .WithMany("SubMenuList")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerBillHistory", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerBillParent", "ConsumerBillParent")
                        .WithMany("ConsumerBillHistoryList")
                        .HasForeignKey("ConsumerBillParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerPaymentInfo", "ConsumerPaymentInfo")
                        .WithMany("ConsumerBillHistoryList")
                        .HasForeignKey("ConsumerPaymentInfoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerBillParent", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("ConsumerBillParentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerMealWiseExtraChitParent", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("ConsumerMealWiseExtraChitParentList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.OrderType", "OrderType")
                        .WithMany("ConsumerMealWiseExtraChitParentList")
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("ConsumerMealWiseExtraChitParentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerMealWiseExtrachit", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerMealWiseExtraChitParent", "ConsumerMealWiseExtraChitParent")
                        .WithMany("ConsumerMealWiseExtrachitList")
                        .HasForeignKey("ConsumerMealWiseExtraChitParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("ConsumerMealWiseExtrachitList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerMonthlyBillRecord", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("ConsumerMonthlyBillRecordList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerPaymentInfo", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ConsumerBillParent", "ConsumerBillParent")
                        .WithMany("ConsumerPaymentInfoList")
                        .HasForeignKey("ConsumerBillParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.PaymentMethod", "PaymentMethod")
                        .WithMany("ConsumerPaymentInfoList")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.CustomerChoice", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", "ExtraItem")
                        .WithMany("CustomerChoiceList")
                        .HasForeignKey("ExtraItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("CustomerChoiceList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.OrderType", "OrderType")
                        .WithMany("CustomerChoiceList")
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("CustomerChoiceList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("CustomerChoiceList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.CustomerChoiceV2", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraChitParent", "ExtraChitParent")
                        .WithMany("CustomerChoiceV2List")
                        .HasForeignKey("ExtraChitParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", "ExtraItem")
                        .WithMany("CustomerChoiceV2List")
                        .HasForeignKey("ExtraItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("CustomerChoiceV2List")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.OnSpotParent", "OnSpotParent")
                        .WithMany("CustomerChoiceV2List")
                        .HasForeignKey("OnSpotParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.OrderType", "OrderType")
                        .WithMany("CustomerChoiceV2List")
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("CustomerChoiceV2List")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("CustomerChoiceV2List")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.CustomerDailyMenuChoice", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", "ExtraItem")
                        .WithMany("CustomerDailyMenuChoiceList")
                        .HasForeignKey("ExtraItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("CustomerDailyMenuChoiceList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.OrderType", "OrderType")
                        .WithMany("CustomerDailyMenuChoiceList")
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("CustomerDailyMenuChoiceList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.DailySetMenu", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("DailySetMenuList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("DailySetMenuList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("ExtraItemList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("ExtraItemList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.MaintenanceBillHistory", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("MaintenanceBillHistoryList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.MenuItem", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", "ExtraItem")
                        .WithMany("MenuItemList")
                        .HasForeignKey("ExtraItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("MenuItemList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("MenuItemList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OnSpotParent", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.Office", "Office")
                        .WithMany("OnSpotParentList")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("OnSpotParentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OrderHistory", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("OrderHistoryList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.OrderHistoryVr2", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("OrderHistoryVr2List")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.OrderType", "OrderType")
                        .WithMany("OrderHistoryVr2List")
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("OrderHistoryVr2List")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("OrderHistoryVr2List")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("OrderHistoryVr2List")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.Period", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("PeriodList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("PeriodList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.PreOrderSchedule", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("PreOrderScheduleList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany()
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("PreOrderScheduleList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.RemainingBalanceAndWeightedPriceCalculation", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", "StoreInItem")
                        .WithMany("RemainingBalanceAndWeightedPriceCalculationList")
                        .HasForeignKey("StoreInItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("SetMenuList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenuDetails", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.ExtraItem", "ExtraItem")
                        .WithMany("SetMenuDetailList")
                        .HasForeignKey("ExtraItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SetMenu", "SetMenu")
                        .WithMany("SetMenuDetailsList")
                        .HasForeignKey("SetMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("SetMenuDetailsList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SpecialMenuOrder", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.SpecialMenuParent", "SpecialMenuParent")
                        .WithMany("SpecialMenuOrderList")
                        .HasForeignKey("SpecialMenuParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("SpecialMenuOrderList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.SpecialMenuParent", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("SpecialMenuParentList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.Office", "Office")
                        .WithMany("SpecialMenuParentList")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("SpecialMenuParentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItemCategory", "StoreInItemCategory")
                        .WithMany("StoreInItemList")
                        .HasForeignKey("StoreInCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.UnitType", "UnitType")
                        .WithMany("StoreInItemList")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemCategory", "StoreOutItemCategory")
                        .WithMany("StoreOutItemList")
                        .HasForeignKey("StoreOutCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItemRecipe", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", "StoreInItem")
                        .WithMany("StoreOutItemRecipeList")
                        .HasForeignKey("StoreInItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreOutItem", "StoreOutItem")
                        .WithMany("StoreOutItemRecipeList")
                        .HasForeignKey("StoreOutItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.UserDateChoiceDetail", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.UserDateChoiceMaster", "UserDateChoiceMaster")
                        .WithMany("UserDateChoiceDetailList")
                        .HasForeignKey("UserDateChoiceMasterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.UserDateChoiceMaster", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.MealType", "MealType")
                        .WithMany("UserDateChoiceMasterList")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("UserDateChoiceMasterList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mess_Management_System_Alpha_V2.Models.MessModels.WarehouseStorage", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Models.MessModels.StoreInItem", "StoreInItem")
                        .WithMany("WarehouseStorageList")
                        .HasForeignKey("StoreInItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mess_Management_System_Alpha_V2.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
